server:
  port: 8085

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.devpulse.*"

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

auth:
  service:
    url: "http://localhost:8081"

notification:
  email:
    from: shopcapital9@gmail.com
  default:
    email: ${DEVELOPER_EMAIL:thakorsarthak2912@gmail.com}

internal:
  service:
    secret: ${INTERNAL_SERVICE_SECRET:devpulse-internal-secret-change-in-prod}
